# Generated by Django 4.1.1 on 2022-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
